[package]
name = "woowgpu"
version = "0.1.0"
authors = ["dyaso <verdys@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.22"
winit = "0.20"
wgpu = "0.6.0"
futures = "0.3.4"

shaderc = "0.6"